kind: Service
apiVersion: v1
metadata:
  name: isfoxonit-nginx
spec:
  selector:
    app: isfoxonit
  ports:
    - name: http
      protocol: "TCP"
      port: 80
      targetPort: 80
    - name: https
      protocol: "TCP"
      port: 443
      targetPort: 443
  type: NodePort
